# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/umair/myGit/Two_Phase_Elasticity

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/umair/myGit/Two_Phase_Elasticity

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/umair/myGit/Two_Phase_Elasticity/CMakeFiles /home/umair/myGit/Two_Phase_Elasticity/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/umair/myGit/Two_Phase_Elasticity/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named info

# Build rule for target.
info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 info
.PHONY : info

# fast build rule for target.
info/fast:
	$(MAKE) -f CMakeFiles/info.dir/build.make CMakeFiles/info.dir/build
.PHONY : info/fast

#=============================================================================
# Target rules for targets named strip_comments

# Build rule for target.
strip_comments: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 strip_comments
.PHONY : strip_comments

# fast build rule for target.
strip_comments/fast:
	$(MAKE) -f CMakeFiles/strip_comments.dir/build.make CMakeFiles/strip_comments.dir/build
.PHONY : strip_comments/fast

#=============================================================================
# Target rules for targets named distclean

# Build rule for target.
distclean: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 distclean
.PHONY : distclean

# fast build rule for target.
distclean/fast:
	$(MAKE) -f CMakeFiles/distclean.dir/build.make CMakeFiles/distclean.dir/build
.PHONY : distclean/fast

#=============================================================================
# Target rules for targets named runclean

# Build rule for target.
runclean: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 runclean
.PHONY : runclean

# fast build rule for target.
runclean/fast:
	$(MAKE) -f CMakeFiles/runclean.dir/build.make CMakeFiles/runclean.dir/build
.PHONY : runclean/fast

#=============================================================================
# Target rules for targets named release

# Build rule for target.
release: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 release
.PHONY : release

# fast build rule for target.
release/fast:
	$(MAKE) -f CMakeFiles/release.dir/build.make CMakeFiles/release.dir/build
.PHONY : release/fast

#=============================================================================
# Target rules for targets named debug

# Build rule for target.
debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 debug
.PHONY : debug

# fast build rule for target.
debug/fast:
	$(MAKE) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/build
.PHONY : debug/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

#=============================================================================
# Target rules for targets named Two_Phase_Elasticity

# Build rule for target.
Two_Phase_Elasticity: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Two_Phase_Elasticity
.PHONY : Two_Phase_Elasticity

# fast build rule for target.
Two_Phase_Elasticity/fast:
	$(MAKE) -f CMakeFiles/Two_Phase_Elasticity.dir/build.make CMakeFiles/Two_Phase_Elasticity.dir/build
.PHONY : Two_Phase_Elasticity/fast

TwoPhaseElastic.o: TwoPhaseElastic.cpp.o

.PHONY : TwoPhaseElastic.o

# target to build an object file
TwoPhaseElastic.cpp.o:
	$(MAKE) -f CMakeFiles/Two_Phase_Elasticity.dir/build.make CMakeFiles/Two_Phase_Elasticity.dir/TwoPhaseElastic.cpp.o
.PHONY : TwoPhaseElastic.cpp.o

TwoPhaseElastic.i: TwoPhaseElastic.cpp.i

.PHONY : TwoPhaseElastic.i

# target to preprocess a source file
TwoPhaseElastic.cpp.i:
	$(MAKE) -f CMakeFiles/Two_Phase_Elasticity.dir/build.make CMakeFiles/Two_Phase_Elasticity.dir/TwoPhaseElastic.cpp.i
.PHONY : TwoPhaseElastic.cpp.i

TwoPhaseElastic.s: TwoPhaseElastic.cpp.s

.PHONY : TwoPhaseElastic.s

# target to generate assembly for a file
TwoPhaseElastic.cpp.s:
	$(MAKE) -f CMakeFiles/Two_Phase_Elasticity.dir/build.make CMakeFiles/Two_Phase_Elasticity.dir/TwoPhaseElastic.cpp.s
.PHONY : TwoPhaseElastic.cpp.s

assemble_system.o: assemble_system.cpp.o

.PHONY : assemble_system.o

# target to build an object file
assemble_system.cpp.o:
	$(MAKE) -f CMakeFiles/Two_Phase_Elasticity.dir/build.make CMakeFiles/Two_Phase_Elasticity.dir/assemble_system.cpp.o
.PHONY : assemble_system.cpp.o

assemble_system.i: assemble_system.cpp.i

.PHONY : assemble_system.i

# target to preprocess a source file
assemble_system.cpp.i:
	$(MAKE) -f CMakeFiles/Two_Phase_Elasticity.dir/build.make CMakeFiles/Two_Phase_Elasticity.dir/assemble_system.cpp.i
.PHONY : assemble_system.cpp.i

assemble_system.s: assemble_system.cpp.s

.PHONY : assemble_system.s

# target to generate assembly for a file
assemble_system.cpp.s:
	$(MAKE) -f CMakeFiles/Two_Phase_Elasticity.dir/build.make CMakeFiles/Two_Phase_Elasticity.dir/assemble_system.cpp.s
.PHONY : assemble_system.cpp.s

grid_dof.o: grid_dof.cpp.o

.PHONY : grid_dof.o

# target to build an object file
grid_dof.cpp.o:
	$(MAKE) -f CMakeFiles/Two_Phase_Elasticity.dir/build.make CMakeFiles/Two_Phase_Elasticity.dir/grid_dof.cpp.o
.PHONY : grid_dof.cpp.o

grid_dof.i: grid_dof.cpp.i

.PHONY : grid_dof.i

# target to preprocess a source file
grid_dof.cpp.i:
	$(MAKE) -f CMakeFiles/Two_Phase_Elasticity.dir/build.make CMakeFiles/Two_Phase_Elasticity.dir/grid_dof.cpp.i
.PHONY : grid_dof.cpp.i

grid_dof.s: grid_dof.cpp.s

.PHONY : grid_dof.s

# target to generate assembly for a file
grid_dof.cpp.s:
	$(MAKE) -f CMakeFiles/Two_Phase_Elasticity.dir/build.make CMakeFiles/Two_Phase_Elasticity.dir/grid_dof.cpp.s
.PHONY : grid_dof.cpp.s

initial_values.o: initial_values.cpp.o

.PHONY : initial_values.o

# target to build an object file
initial_values.cpp.o:
	$(MAKE) -f CMakeFiles/Two_Phase_Elasticity.dir/build.make CMakeFiles/Two_Phase_Elasticity.dir/initial_values.cpp.o
.PHONY : initial_values.cpp.o

initial_values.i: initial_values.cpp.i

.PHONY : initial_values.i

# target to preprocess a source file
initial_values.cpp.i:
	$(MAKE) -f CMakeFiles/Two_Phase_Elasticity.dir/build.make CMakeFiles/Two_Phase_Elasticity.dir/initial_values.cpp.i
.PHONY : initial_values.cpp.i

initial_values.s: initial_values.cpp.s

.PHONY : initial_values.s

# target to generate assembly for a file
initial_values.cpp.s:
	$(MAKE) -f CMakeFiles/Two_Phase_Elasticity.dir/build.make CMakeFiles/Two_Phase_Elasticity.dir/initial_values.cpp.s
.PHONY : initial_values.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Two_Phase_Elasticity.dir/build.make CMakeFiles/Two_Phase_Elasticity.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Two_Phase_Elasticity.dir/build.make CMakeFiles/Two_Phase_Elasticity.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Two_Phase_Elasticity.dir/build.make CMakeFiles/Two_Phase_Elasticity.dir/main.cpp.s
.PHONY : main.cpp.s

quadrature_point_history.o: quadrature_point_history.cpp.o

.PHONY : quadrature_point_history.o

# target to build an object file
quadrature_point_history.cpp.o:
	$(MAKE) -f CMakeFiles/Two_Phase_Elasticity.dir/build.make CMakeFiles/Two_Phase_Elasticity.dir/quadrature_point_history.cpp.o
.PHONY : quadrature_point_history.cpp.o

quadrature_point_history.i: quadrature_point_history.cpp.i

.PHONY : quadrature_point_history.i

# target to preprocess a source file
quadrature_point_history.cpp.i:
	$(MAKE) -f CMakeFiles/Two_Phase_Elasticity.dir/build.make CMakeFiles/Two_Phase_Elasticity.dir/quadrature_point_history.cpp.i
.PHONY : quadrature_point_history.cpp.i

quadrature_point_history.s: quadrature_point_history.cpp.s

.PHONY : quadrature_point_history.s

# target to generate assembly for a file
quadrature_point_history.cpp.s:
	$(MAKE) -f CMakeFiles/Two_Phase_Elasticity.dir/build.make CMakeFiles/Two_Phase_Elasticity.dir/quadrature_point_history.cpp.s
.PHONY : quadrature_point_history.cpp.s

run.o: run.cpp.o

.PHONY : run.o

# target to build an object file
run.cpp.o:
	$(MAKE) -f CMakeFiles/Two_Phase_Elasticity.dir/build.make CMakeFiles/Two_Phase_Elasticity.dir/run.cpp.o
.PHONY : run.cpp.o

run.i: run.cpp.i

.PHONY : run.i

# target to preprocess a source file
run.cpp.i:
	$(MAKE) -f CMakeFiles/Two_Phase_Elasticity.dir/build.make CMakeFiles/Two_Phase_Elasticity.dir/run.cpp.i
.PHONY : run.cpp.i

run.s: run.cpp.s

.PHONY : run.s

# target to generate assembly for a file
run.cpp.s:
	$(MAKE) -f CMakeFiles/Two_Phase_Elasticity.dir/build.make CMakeFiles/Two_Phase_Elasticity.dir/run.cpp.s
.PHONY : run.cpp.s

solve_and_output.o: solve_and_output.cpp.o

.PHONY : solve_and_output.o

# target to build an object file
solve_and_output.cpp.o:
	$(MAKE) -f CMakeFiles/Two_Phase_Elasticity.dir/build.make CMakeFiles/Two_Phase_Elasticity.dir/solve_and_output.cpp.o
.PHONY : solve_and_output.cpp.o

solve_and_output.i: solve_and_output.cpp.i

.PHONY : solve_and_output.i

# target to preprocess a source file
solve_and_output.cpp.i:
	$(MAKE) -f CMakeFiles/Two_Phase_Elasticity.dir/build.make CMakeFiles/Two_Phase_Elasticity.dir/solve_and_output.cpp.i
.PHONY : solve_and_output.cpp.i

solve_and_output.s: solve_and_output.cpp.s

.PHONY : solve_and_output.s

# target to generate assembly for a file
solve_and_output.cpp.s:
	$(MAKE) -f CMakeFiles/Two_Phase_Elasticity.dir/build.make CMakeFiles/Two_Phase_Elasticity.dir/solve_and_output.cpp.s
.PHONY : solve_and_output.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... info"
	@echo "... edit_cache"
	@echo "... strip_comments"
	@echo "... distclean"
	@echo "... runclean"
	@echo "... release"
	@echo "... debug"
	@echo "... run"
	@echo "... Two_Phase_Elasticity"
	@echo "... TwoPhaseElastic.o"
	@echo "... TwoPhaseElastic.i"
	@echo "... TwoPhaseElastic.s"
	@echo "... assemble_system.o"
	@echo "... assemble_system.i"
	@echo "... assemble_system.s"
	@echo "... grid_dof.o"
	@echo "... grid_dof.i"
	@echo "... grid_dof.s"
	@echo "... initial_values.o"
	@echo "... initial_values.i"
	@echo "... initial_values.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... quadrature_point_history.o"
	@echo "... quadrature_point_history.i"
	@echo "... quadrature_point_history.s"
	@echo "... run.o"
	@echo "... run.i"
	@echo "... run.s"
	@echo "... solve_and_output.o"
	@echo "... solve_and_output.i"
	@echo "... solve_and_output.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

